### ISSUE TITLE
Make sure RubyMotion is using a valid (non-expired) provisioning profile

### ISSUE THREAD

**Issue by dotvo007** [HipByte/motion-provisioning#10]
Hi, I've used this gem to create a .mobileprovision certificate when running `rake device`. It didn't work as expected, though. Neither Xcode nor iTunes were running at the time. Furthermore there wasn't an error message about not specified device identifier, so I guess this should be fine.

I'm using `OSX 10.11.6 El Capitan` and `iOS 10.0.2`.

This is the error message:

```
Error when starting debug server service: code -402653150
Make sure RubyMotion is using a valid (non-expired) provisioning profile
and that no other process (iTunes, Xcode) is connected to your iOS device
at the same time (even through Wi-Fi).
```

What else could be the reason for this error? Could this be connected to the initial certificate, which is created via the keychain wizard? I've closely followed instructions here.

Thanks!

**Comment by MarkVillacampa** [comment]
Make sure the entitlements in your .mobileprovision file (it's an XML, you can open it with a text editor) and the ones specified in your Rakefile via `app.entitlements['foo'] = 'bar'` match.

**Comment by dotvo007** [comment]
The problem has been resolved now thanks to a great developer who had helped me via Screenhero.
He found out that in X-code I had not yet joined a developer team. After doing that a developer certificate was created and copied into the signing folder of the app. Then its name was written into the Rakefile (app.development). Thanks!

**Comment by jwg2s** [comment]
@MarkVillacampa this gets me every time.  Thanks for the correct answer.
