### ISSUE TITLE
Error provisioning

### ISSUE THREAD

**Issue by mark-watson** [HipByte/motion-provisioning#19]
I get an SMS message to OK login, but before I can respond, the rake task errors out (I changed my email to dummy value MYACCOUNT before pasting the following):

$ rake
Couldn't verify that spaceship is up to date
      Info Logging into the Developer Portal with email 'MYACCOUNT@mac.com'.
rake aborted!
Invalid 2 step response {"trustedPhoneNumbers"=>[{ ... STUFF DELETED HERE ...}}
/usr/local/lib/ruby/gems/2.4.0/gems/spaceship-0.39.0/lib/spaceship/two_step_client.rb:41:in `handle_two_step'
/usr/local/lib/ruby/gems/2.4.0/gems/spaceship-0.39.0/lib/spaceship/client.rb:316:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.4.0/gems/spaceship-0.39.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/usr/local/lib/ruby/gems/2.4.0/gems/spaceship-0.39.0/lib/spaceship/client.rb:430:in `do_login'
/usr/local/lib/ruby/gems/2.4.0/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:69:in `client'
/usr/local/lib/ruby/gems/2.4.0/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:6:in `client'
/usr/local/lib/ruby/gems/2.4.0/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:39:in `certificate_name'
/usr/local/lib/ruby/gems/2.4.0/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:206:in `certificate'
/Users/markw/BITBUCKET/ios_cookingspace/Rakefile:23:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in `development'
/Users/markw/BITBUCKET/ios_cookingspace/Rakefile:21:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project/template/ios.rb:156:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => simulator

**Comment by Youngv** [comment]
same error

**Comment by mipmip** [comment]
same here

**Comment by nickyhajal** [comment]
Hitting this issue as well - any way around it?

**Comment by amirrajan** [comment]
Possibly [related](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth)?

**Comment by thbar** [comment]
@amirrajan I tried that but I'm still facing the error reported by @mark-watson.

**Comment by andrewhavens** [comment]
This should be fixed now in version 1.0.0.
