### ISSUE TITLE
does not work with new required 2 factor authentication

### ISSUE THREAD

**Issue by spnkr** [HipByte/motion-provisioning#28]
now that apple requires 2 factor auth for apple developer account apple IDs, motion-provisioning says 'invalid password' on build.

```
Info Using certificate 'iPhone Developer: NAME (----------)'.
      Info The login information you enter will be stored safely in the macOS keychain.
      Info Password for foo@bar.com: *************
security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
      Info Logging into the Developer Portal with email 'foo@bar.com'.
     Error There was an error logging into your account. Your password may be wrong.
      Info Do you want to reenter your password? (Y/n): n
```

yes, i enabled 2 factor auth for this apple id.

**Comment by andrewhavens** [comment]
What version of the motion-provisioning gem are you using?

**Comment by cmckni3** [comment]
May require a newer version of fastlane. What version of motion-provisioning and fastlane are installed?

**Comment by andrewhavens** [comment]
I'm going to close this because I'm pretty sure it's an issue with not using the latest versions of motion-provisioning and fastlane. @spnkr Feel free to re-open this if you continue to have this issue after upgrading.
