### ISSUE TITLE
Spaceship 0.31.9 causes ArgumentError when calling ensure_csrf

### ISSUE THREAD

**Issue by danhealy** [HipByte/motion-provisioning#5]
```
   Warning Couldn't find any existing certificates... creating a new one.
rake aborted!
ArgumentError: wrong number of arguments (0 for 1)
/Users/dan/.rvm/gems/ruby-2.2.4@tv-os/gems/spaceship-0.31.9/lib/spaceship/portal/portal_client.rb:427:in `ensure_csrf'
/Users/dan/.rvm/gems/ruby-2.2.4@tv-os/gems/motion-provisioning-0.0.3/lib/motion-provisioning/spaceship/portal_client.rb:20:in `create_certificate!'
```

Seems they are actively working on this today:

https://github.com/fastlane/fastlane/commit/2284e794843538910f711c1f85f08b6b886a5a04#diff-039fca4abe1ab7d3789453780230a0b3R427

Specifying spaceship version 0.31.8 in my gemfile works for now

**Comment by MarkVillacampa** [comment]
Thanks for the report!

This issue should be solved by a58fe030b7735126b6be642798260ac6eeb2d26d.

I've released motion-provisioning 0.0.4 which includes this fix.
